// <auto-generated />
namespace CrmBl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class m10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m10));
        
        string IMigrationMetadata.Id
        {
            get { return "202005051724359_m1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
